### ISSUE TITLE
✨ [FEAT] 수강신청 구현

### ISSUE THREAD

**Issue by yeon2lee** [2024Hanium-Allclear/Lecture#20]
## 📝 개요
- 수강 신청 기능 개발

## ✔️ To-Do
- [x] 수강 신청 API
- [x] 수강 취소 API
- [x] 수강 신청 내역 조회 API

## ⏰ 예상 소요 시간
- 2024.9.12까지 완료 예정
